name: BetterBans
version: 0.1-beta
main: ca.edwardvo.betterbans.BetterBans
author: eddy5641


commands:
  dbg:
    description: Used to debug data
    usage: /dbg
  ban:
    description: Used to issue ban and tempbans to players
    usage: /ban <player name>
  ban-ip:
    description: Does the exact same thing as /ban but doesn't show the 2nd menu
    usage: /ban-ip <player name>
  banip:
    description: Bans an ip address
    usage: /banip <ip address>
  banlist:
    description: Lists all bans
    usage: /banlist
  findban:
    description: Finds a ban
  kick:
    descrption: Kicks a player from the server
    usage: /kick
    usage: /kick <player name>
depend: [ProtocolLib]
permissions:
    bb.ban:
        description: Allows a player to ban others.
        default: op
    bb.unban:
        description: Allows a player to unban others.
        default: op
    bb.tempban:
        description: Allows a player to tempban others.
        default: op
    bb.tempipban:
        description: Allows a player to temp IP ban others.
        default: op
    bb.ipban:
        description: Allows a player to IP ban others
        default: op
    bb.kick:
        description: Allows a player to kick others with a reason
        default: op
    bb.warn:
        description: Allows a player to give out warnings to others.
        default: op
    bb.rmwarn.nonself:
        description: Allows a player to remove warnings that are not on themself
        default: op
    bb.rmwarn.nself:
        description: Allows a player to remove warnings that appied to them
        default: op
    bb.immune:
        description: Makes a player unpunishable
        default: op
    bb.mute:
        description: Allows a player issue and remove chat punishments
        default: op
    bb.checkpun:
        description: Allows a player to check any punishments
        default: true
    bb.getip:
        descriptions: Allows a player to get another players IP address
        default: op
    bb.dupeip:
        description: Allows a player to check other accounts that use the same IP address as the given one
        default: op
    bb.clearwarnings:
        description: Allows a player to delete all warnings for a given player.
        default: op
    bb.lockdown.ip:
        description: Allows a player to lockdown the server to player ips that have joined the server
        default: op
    bb.lockdown.use:
        description: Allows a player to lockdown the server
        default: op
    bb.lockdown.bypass:
        description: Allows a player to enter the server if lockdown is enabled
        default: op
    bb.pban:
        description: Allows a player to make a ban public
        default: op