name: BetterBans
version: 0.1-beta
main: ca.edwardvo.betterbans.BetterBans
author: eddy5641


commands:
  dbg:
    description: Used to debug data
    usage: /dbg
  ban:
    description: Used to issue ban and tempbans to players
    usage: /ban <player name>